// ==================== CONNECTOR REGISTRY ====================
// Definiciones estáticas de conectores disponibles: metadata, scopes y acciones.

import type { ConnectorDefinition, IntegrationSource } from "./types";

export const CONNECTOR_DEFINITIONS: Record<IntegrationSource, ConnectorDefinition> = {
  figma: {
    source: "figma",
    name: "Figma",
    description: "Importar diseños de Figma",
    type: "rest",
    priority: "high",
    scopes: ["file_read"],
    actions: [
      { name: "listFiles", description: "Listar archivos recientes", params: [{ name: "limit", type: "number", required: false, description: "Máximo de archivos" }] },
      { name: "getFile", description: "Obtener detalle de un archivo", params: [{ name: "fileKey", type: "string", required: true }] },
    ],
    supportsOAuth: false,
    supportsApiKey: true,
  },
  local: {
    source: "local",
    name: "Archivos locales",
    description: "Subir y gestionar archivos locales",
    type: "rest",
    priority: "high",
    scopes: [],
    actions: [
      { name: "upload", description: "Subir un archivo", params: [{ name: "file", type: "object", required: true }] },
      { name: "list", description: "Listar archivos subidos", params: [] },
    ],
    supportsOAuth: false,
    supportsApiKey: false,
  },
  onedrive: {
    source: "onedrive",
    name: "OneDrive",
    description: "Importar archivos de OneDrive",
    type: "oauth2",
    priority: "medium",
    scopes: ["Files.Read"],
    actions: [{ name: "listFiles", description: "Listar archivos", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
    authUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
  },
  "google-drive": {
    source: "google-drive",
    name: "Google Drive",
    description: "Leer y escribir archivos en Google Drive",
    type: "oauth2",
    priority: "medium",
    scopes: [
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly",
    ],
    actions: [
      { name: "listFiles", description: "Listar archivos", params: [{ name: "limit", type: "number", required: false }, { name: "query", type: "string", required: false }] },
      { name: "getResource", description: "Obtener detalle de un archivo", params: [{ name: "id", type: "string", required: true }] },
      { name: "readFile", description: "Leer contenido de un archivo", params: [{ name: "id", type: "string", required: true }] },
      { name: "createFile", description: "Crear un nuevo archivo", params: [{ name: "name", type: "string", required: true }, { name: "content", type: "string", required: true }, { name: "mimeType", type: "string", required: false }, { name: "folderId", type: "string", required: false }] },
      { name: "updateFile", description: "Actualizar contenido de un archivo existente", params: [{ name: "id", type: "string", required: true }, { name: "content", type: "string", required: true }] },
      { name: "deleteFile", description: "Eliminar un archivo", params: [{ name: "id", type: "string", required: true }] },
      { name: "createFolder", description: "Crear una carpeta", params: [{ name: "name", type: "string", required: true }, { name: "parentId", type: "string", required: false }] },
    ],
    supportsOAuth: true,
    supportsApiKey: false,
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
  },
  skill: {
    source: "skill",
    name: "Habilidades",
    description: "Habilidades internas del agente",
    type: "rest",
    priority: "low",
    scopes: [],
    actions: [
      { name: "listSkills", description: "Listar habilidades disponibles", params: [] },
      { name: "executeSkill", description: "Ejecutar una habilidad por nombre", params: [{ name: "name", type: "string", required: true }, { name: "action", type: "string", required: false, description: "Acción específica de la habilidad (ej. 'execute', 'info')" }, { name: "params", type: "object", required: false, description: "Parámetros adicionales para la habilidad" }] },
    ],
    supportsOAuth: false,
    supportsApiKey: false,
  },
  slack: {
    source: "slack",
    name: "Slack",
    description: "Mensajes, canales y reacciones",
    type: "oauth2",
    priority: "high",
    scopes: ["chat:write", "channels:read", "users:read", "reactions:write", "files:write"],
    actions: [
      { name: "sendMessage", description: "Enviar mensaje a un canal", params: [{ name: "channel", type: "string", required: true }, { name: "text", type: "string", required: true }, { name: "threadTs", type: "string", required: false }] },
      { name: "listChannels", description: "Listar canales", params: [{ name: "limit", type: "number", required: false }] },
      { name: "getChannelHistory", description: "Obtener historial de un canal", params: [{ name: "channel", type: "string", required: true }, { name: "limit", type: "number", required: false }] },
      { name: "addReaction", description: "Agregar reacción a un mensaje", params: [{ name: "channel", type: "string", required: true }, { name: "timestamp", type: "string", required: true }, { name: "emoji", type: "string", required: true }] },
      { name: "uploadFile", description: "Subir archivo a un canal", params: [{ name: "channel", type: "string", required: true }, { name: "content", type: "string", required: true }, { name: "filename", type: "string", required: true }] },
      { name: "listUsers", description: "Listar usuarios del workspace", params: [{ name: "limit", type: "number", required: false }] },
    ],
    supportsOAuth: true,
    supportsApiKey: true,
    authUrl: "https://slack.com/oauth/v2/authorize",
    tokenUrl: "https://slack.com/api/oauth.v2.access",
  },
  gmail: {
    source: "gmail",
    name: "Gmail",
    description: "Leer, enviar y gestionar emails",
    type: "oauth2",
    priority: "high",
    scopes: ["https://www.googleapis.com/auth/gmail.send", "https://www.googleapis.com/auth/gmail.readonly", "https://www.googleapis.com/auth/gmail.modify"],
    actions: [
      { name: "sendEmail", description: "Enviar email", params: [{ name: "to", type: "string", required: true }, { name: "subject", type: "string", required: true }, { name: "body", type: "string", required: true }, { name: "html", type: "boolean", required: false }, { name: "cc", type: "string", required: false }] },
      { name: "listEmails", description: "Listar emails recientes", params: [{ name: "query", type: "string", required: false }, { name: "limit", type: "number", required: false }] },
      { name: "getEmail", description: "Obtener contenido de un email", params: [{ name: "messageId", type: "string", required: true }] },
      { name: "archiveEmail", description: "Archivar un email", params: [{ name: "messageId", type: "string", required: true }] },
      { name: "deleteEmail", description: "Eliminar un email", params: [{ name: "messageId", type: "string", required: true }] },
      { name: "listLabels", description: "Listar etiquetas", params: [] },
      { name: "createDraft", description: "Crear borrador de email", params: [{ name: "to", type: "string", required: true }, { name: "subject", type: "string", required: true }, { name: "body", type: "string", required: true }] },
    ],
    supportsOAuth: true,
    supportsApiKey: false,
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
  },
  github: {
    source: "github",
    name: "GitHub",
    description: "Issues, repos, PRs y archivos",
    type: "oauth2",
    priority: "high",
    scopes: ["repo", "read:user", "user:email"],
    actions: [
      { name: "listRepos", description: "Listar repositorios", params: [{ name: "limit", type: "number", required: false }] },
      { name: "listRepoContent", description: "Listar contenido (archivos y carpetas) de un repositorio", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "path", type: "string", required: false, description: "Ruta dentro del repo (default: raiz)" }, { name: "branch", type: "string", required: false }] },
      { name: "readFile", description: "Leer contenido de un archivo del repositorio", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "path", type: "string", required: true }, { name: "branch", type: "string", required: false }] },
      { name: "createIssue", description: "Crear un issue", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "title", type: "string", required: true }, { name: "body", type: "string", required: false }] },
      { name: "closeIssue", description: "Cerrar un issue", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "issueNumber", type: "number", required: true }] },
      { name: "listIssues", description: "Listar issues de un repositorio", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "state", type: "string", required: false }] },
      { name: "createFile", description: "Crear o actualizar un archivo en el repo", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "path", type: "string", required: true }, { name: "content", type: "string", required: true }, { name: "message", type: "string", required: true }, { name: "branch", type: "string", required: false }] },
      { name: "updateFile", description: "Actualizar el contenido de un archivo existente (requiere sha, se autodetecta si falta)", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "path", type: "string", required: true }, { name: "content", type: "string", required: true }, { name: "message", type: "string", required: true }, { name: "branch", type: "string", required: false }, { name: "sha", type: "string", required: false }] },
      { name: "deleteFile", description: "Eliminar un archivo del repositorio", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "path", type: "string", required: true }, { name: "message", type: "string", required: true }, { name: "branch", type: "string", required: false }] },
      { name: "createPR", description: "Crear un Pull Request", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "title", type: "string", required: true }, { name: "head", type: "string", required: true }, { name: "base", type: "string", required: true }, { name: "body", type: "string", required: false }] },
      { name: "listPRs", description: "Listar Pull Requests del repositorio", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "state", type: "string", required: false }, { name: "limit", type: "number", required: false }] },
      { name: "getPR", description: "Obtener detalle de un Pull Request", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "prNumber", type: "number", required: true }] },
      { name: "closePR", description: "Cerrar un Pull Request", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "prNumber", type: "number", required: true }] },
      { name: "mergePR", description: "Merge de un Pull Request", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "prNumber", type: "number", required: true }, { name: "commitTitle", type: "string", required: false }, { name: "commitMessage", type: "string", required: false }, { name: "mergeMethod", type: "string", required: false }] },
      { name: "createReview", description: "Aprobar, comentar o pedir cambios en un PR", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "prNumber", type: "number", required: true }, { name: "event", type: "string", required: true }, { name: "body", type: "string", required: false }] },
      { name: "listBranches", description: "Listar ramas del repositorio", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "limit", type: "number", required: false }] },
      { name: "createBranch", description: "Crear una nueva rama a partir de otra existente o de la rama por defecto", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "branch", type: "string", required: true }, { name: "fromBranch", type: "string", required: false }] },
      { name: "listCommits", description: "Listar commits de un repositorio (opcionalmente de una rama)", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "branch", type: "string", required: false }, { name: "limit", type: "number", required: false }] },
      { name: "getRepo", description: "Obtener detalle de un repositorio", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }] },
      { name: "getReadme", description: "Leer el README del repositorio", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "branch", type: "string", required: false }] },
      { name: "getIssue", description: "Obtener detalle de un issue", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "issueNumber", type: "number", required: true }] },
      { name: "updateIssue", description: "Actualizar título/cuerpo/estado/labels de un issue", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "issueNumber", type: "number", required: true }, { name: "title", type: "string", required: false }, { name: "body", type: "string", required: false }, { name: "state", type: "string", required: false }, { name: "labels", type: "array", required: false }, { name: "assignees", type: "array", required: false }] },
      { name: "addIssueComment", description: "Agregar un comentario a un issue", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "issueNumber", type: "number", required: true }, { name: "body", type: "string", required: true }] },
      { name: "searchCode", description: "Buscar código dentro de un repositorio o usuario", params: [{ name: "q", type: "string", required: true }, { name: "owner", type: "string", required: false }, { name: "repo", type: "string", required: false }, { name: "limit", type: "number", required: false }] },
      { name: "searchRepositories", description: "Buscar repositorios públicos por texto", params: [{ name: "q", type: "string", required: true }, { name: "limit", type: "number", required: false }] },
      { name: "getAuthenticatedUser", description: "Obtener info del usuario autenticado (login, nombre, avatar)", params: [] },
    ],
    supportsOAuth: true,
    supportsApiKey: true,
    authUrl: "https://github.com/login/oauth/authorize",
    tokenUrl: "https://github.com/login/oauth/access_token",
  },
  notion: {
    source: "notion",
    name: "Notion",
    description: "Leer, crear y actualizar páginas y bases de datos",
    type: "oauth2",
    priority: "high",
    scopes: [],
    actions: [
      { name: "listPages", description: "Listar páginas", params: [{ name: "limit", type: "number", required: false }] },
      { name: "getPage", description: "Obtener contenido de una página", params: [{ name: "pageId", type: "string", required: true }] },
      { name: "createPage", description: "Crear página", params: [{ name: "parentId", type: "string", required: true }, { name: "title", type: "string", required: true }, { name: "content", type: "string", required: false }] },
      { name: "updatePage", description: "Actualizar título o propiedades de una página", params: [{ name: "pageId", type: "string", required: true }, { name: "title", type: "string", required: false }, { name: "archived", type: "boolean", required: false }] },
      { name: "appendBlocks", description: "Agregar bloques de contenido a una página", params: [{ name: "pageId", type: "string", required: true }, { name: "content", type: "string", required: true }] },
      { name: "deletePage", description: "Archivar (eliminar) una página", params: [{ name: "pageId", type: "string", required: true }] },
      { name: "searchPages", description: "Buscar páginas por texto", params: [{ name: "query", type: "string", required: true }] },
    ],
    supportsOAuth: true,
    supportsApiKey: true,
    authUrl: "https://api.notion.com/v1/oauth/authorize",
    tokenUrl: "https://api.notion.com/v1/oauth/token",
  },
  "google-sheets": {
    source: "google-sheets",
    name: "Google Sheets",
    description: "Lectura/escritura de datos",
    type: "oauth2",
    priority: "high",
    scopes: ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive.readonly"],
    actions: [
      { name: "listSpreadsheets", description: "Listar hojas de cálculo", params: [{ name: "limit", type: "number", required: false }] },
      { name: "readRange", description: "Leer rango", params: [{ name: "spreadsheetId", type: "string", required: true }, { name: "range", type: "string", required: true }] },
      { name: "writeRange", description: "Escribir rango", params: [{ name: "spreadsheetId", type: "string", required: true }, { name: "range", type: "string", required: true }, { name: "values", type: "array", required: true }] },
    ],
    supportsOAuth: true,
    supportsApiKey: false,
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
  },
  discord: {
    source: "discord",
    name: "Discord",
    description: "Mensajes",
    type: "bot",
    priority: "medium",
    scopes: ["bot"],
    actions: [
      { name: "sendMessage", description: "Enviar mensaje a un canal", params: [{ name: "channelId", type: "string", required: true }, { name: "content", type: "string", required: true }] },
    ],
    supportsOAuth: true,
    supportsApiKey: true,
    authUrl: "https://discord.com/oauth2/authorize",
    tokenUrl: "https://discord.com/api/oauth2/token",
  },
  telegram: {
    source: "telegram",
    name: "Telegram",
    description: "Mensajes vía Bot API",
    type: "bot",
    priority: "medium",
    scopes: [],
    actions: [
      { name: "sendMessage", description: "Enviar mensaje", params: [{ name: "chatId", type: "string", required: true }, { name: "text", type: "string", required: true }] },
    ],
    supportsOAuth: false,
    supportsApiKey: true,
  },
  // --- eCommerce ---
  shopify: {
    source: "shopify",
    name: "Shopify",
    description: "Gestión de productos y órdenes",
    type: "rest",
    priority: "low",
    scopes: ["read_products", "read_orders"],
    actions: [
      { name: "listProducts", description: "Listar productos", params: [{ name: "limit", type: "number", required: false }] },
    ],
    supportsOAuth: true,
    supportsApiKey: true,
  },
  stripe: {
    source: "stripe",
    name: "Stripe",
    description: "Pagos y clientes",
    type: "rest",
    priority: "low",
    scopes: [],
    actions: [
      { name: "listCustomers", description: "Listar clientes", params: [{ name: "limit", type: "number", required: false }] },
    ],
    supportsOAuth: false,
    supportsApiKey: true,
  },
  paypal: {
    source: "paypal",
    name: "PayPal",
    description: "Pagos",
    type: "oauth2",
    priority: "low",
    scopes: ["openid", "profile", "email"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  woocommerce: {
    source: "woocommerce",
    name: "WooCommerce",
    description: "Productos y órdenes de WooCommerce",
    type: "rest",
    priority: "low",
    scopes: [],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: false,
    supportsApiKey: true,
  },
  square: {
    source: "square",
    name: "Square",
    description: "Pagos y catálogo",
    type: "oauth2",
    priority: "low",
    scopes: ["ITEMS_READ", "ORDERS_READ", "CUSTOMERS_READ"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  // --- CRM / Marketing ---
  salesforce: {
    source: "salesforce",
    name: "Salesforce",
    description: "CRM: contactos, leads y oportunidades",
    type: "oauth2",
    priority: "medium",
    scopes: ["api", "refresh_token"],
    actions: [
      { name: "listContacts", description: "Listar contactos", params: [{ name: "limit", type: "number", required: false }, { name: "search", type: "string", required: false }] },
      { name: "createContact", description: "Crear contacto", params: [{ name: "firstName", type: "string", required: false }, { name: "lastName", type: "string", required: true }, { name: "email", type: "string", required: false }, { name: "phone", type: "string", required: false }, { name: "company", type: "string", required: false }] },
      { name: "listLeads", description: "Listar leads", params: [{ name: "limit", type: "number", required: false }] },
      { name: "createLead", description: "Crear lead", params: [{ name: "firstName", type: "string", required: false }, { name: "lastName", type: "string", required: true }, { name: "company", type: "string", required: true }, { name: "email", type: "string", required: false }] },
      { name: "listOpportunities", description: "Listar oportunidades", params: [{ name: "limit", type: "number", required: false }] },
      { name: "createOpportunity", description: "Crear oportunidad", params: [{ name: "name", type: "string", required: true }, { name: "stage", type: "string", required: true }, { name: "closeDate", type: "string", required: true }, { name: "amount", type: "number", required: false }] },
      { name: "runQuery", description: "Ejecutar consulta SOQL", params: [{ name: "query", type: "string", required: true }] },
    ],
    supportsOAuth: true,
    supportsApiKey: false,
    authUrl: "https://login.salesforce.com/services/oauth2/authorize",
    tokenUrl: "https://login.salesforce.com/services/oauth2/token",
  },
  hubspot: {
    source: "hubspot",
    name: "HubSpot",
    description: "CRM: contactos, deals y empresas",
    type: "oauth2",
    priority: "medium",
    scopes: ["crm.objects.contacts.read", "crm.objects.contacts.write", "crm.objects.deals.read", "crm.objects.deals.write", "crm.objects.companies.read"],
    actions: [
      { name: "listContacts", description: "Listar contactos", params: [{ name: "limit", type: "number", required: false }] },
      { name: "createContact", description: "Crear contacto", params: [{ name: "email", type: "string", required: true }, { name: "firstName", type: "string", required: false }, { name: "lastName", type: "string", required: false }, { name: "phone", type: "string", required: false }] },
      { name: "listDeals", description: "Listar deals", params: [{ name: "limit", type: "number", required: false }] },
      { name: "createDeal", description: "Crear deal", params: [{ name: "dealName", type: "string", required: true }, { name: "stage", type: "string", required: true }, { name: "amount", type: "number", required: false }, { name: "closeDate", type: "string", required: false }] },
      { name: "listCompanies", description: "Listar empresas", params: [{ name: "limit", type: "number", required: false }] },
      { name: "searchCRM", description: "Buscar en el CRM", params: [{ name: "objectType", type: "string", required: true }, { name: "query", type: "string", required: true }] },
    ],
    supportsOAuth: true,
    supportsApiKey: true,
    authUrl: "https://app.hubspot.com/oauth/authorize",
    tokenUrl: "https://api.hubapi.com/oauth/v1/token",
  },
  mailchimp: {
    source: "mailchimp",
    name: "Mailchimp",
    description: "Email marketing",
    type: "oauth2",
    priority: "low",
    scopes: [],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: true,
  },
  klaviyo: {
    source: "klaviyo",
    name: "Klaviyo",
    description: "Email/SMS marketing",
    type: "oauth2",
    priority: "low",
    scopes: ["accounts:read", "lists:read", "profiles:read"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  pipedrive: {
    source: "pipedrive",
    name: "Pipedrive",
    description: "CRM de ventas",
    type: "oauth2",
    priority: "low",
    scopes: ["base", "deals:full", "contacts:full"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: true,
  },
  // --- Dev / Project Management ---
  gitlab: {
    source: "gitlab",
    name: "GitLab",
    description: "Repositorios e issues",
    type: "oauth2",
    priority: "low",
    scopes: ["api", "read_user"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: true,
  },
  jira: {
    source: "jira",
    name: "Jira",
    description: "Issues, sprints y proyectos",
    type: "oauth2",
    priority: "medium",
    scopes: ["read:jira-work", "write:jira-work", "read:me"],
    actions: [
      { name: "listProjects", description: "Listar proyectos", params: [{ name: "limit", type: "number", required: false }] },
      { name: "listIssues", description: "Listar issues de un proyecto", params: [{ name: "projectKey", type: "string", required: true }, { name: "status", type: "string", required: false }, { name: "limit", type: "number", required: false }] },
      { name: "getIssue", description: "Obtener detalle de un issue", params: [{ name: "issueKey", type: "string", required: true }] },
      { name: "createIssue", description: "Crear un issue", params: [{ name: "projectKey", type: "string", required: true }, { name: "summary", type: "string", required: true }, { name: "description", type: "string", required: false }, { name: "issueType", type: "string", required: false }, { name: "priority", type: "string", required: false }] },
      { name: "updateIssue", description: "Actualizar un issue", params: [{ name: "issueKey", type: "string", required: true }, { name: "summary", type: "string", required: false }, { name: "status", type: "string", required: false }, { name: "assignee", type: "string", required: false }] },
      { name: "addComment", description: "Agregar comentario a un issue", params: [{ name: "issueKey", type: "string", required: true }, { name: "body", type: "string", required: true }] },
      { name: "transitionIssue", description: "Cambiar estado de un issue", params: [{ name: "issueKey", type: "string", required: true }, { name: "transitionName", type: "string", required: true }] },
    ],
    supportsOAuth: true,
    supportsApiKey: true,
    authUrl: "https://auth.atlassian.com/authorize",
    tokenUrl: "https://auth.atlassian.com/oauth/token",
  },
  linear: {
    source: "linear",
    name: "Linear",
    description: "Gestión de issues",
    type: "oauth2",
    priority: "low",
    scopes: ["read", "write"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  vercel: {
    source: "vercel",
    name: "Vercel",
    description: "Despliegues y proyectos",
    type: "oauth2",
    priority: "low",
    scopes: ["projects", "deployments"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  // --- Productivity ---
  asana: {
    source: "asana",
    name: "Asana",
    description: "Tareas, proyectos y equipos",
    type: "oauth2",
    priority: "medium",
    scopes: ["default"],
    actions: [
      { name: "listProjects", description: "Listar proyectos", params: [{ name: "workspace", type: "string", required: false }] },
      { name: "listTasks", description: "Listar tareas de un proyecto", params: [{ name: "projectId", type: "string", required: true }, { name: "completed", type: "boolean", required: false }] },
      { name: "getTask", description: "Obtener detalle de una tarea", params: [{ name: "taskId", type: "string", required: true }] },
      { name: "createTask", description: "Crear una tarea", params: [{ name: "projectId", type: "string", required: true }, { name: "name", type: "string", required: true }, { name: "notes", type: "string", required: false }, { name: "dueOn", type: "string", required: false }, { name: "assignee", type: "string", required: false }] },
      { name: "updateTask", description: "Actualizar una tarea", params: [{ name: "taskId", type: "string", required: true }, { name: "name", type: "string", required: false }, { name: "completed", type: "boolean", required: false }, { name: "notes", type: "string", required: false }] },
      { name: "deleteTask", description: "Eliminar una tarea", params: [{ name: "taskId", type: "string", required: true }] },
      { name: "addComment", description: "Agregar comentario a una tarea", params: [{ name: "taskId", type: "string", required: true }, { name: "text", type: "string", required: true }] },
    ],
    supportsOAuth: true,
    supportsApiKey: true,
    authUrl: "https://app.asana.com/-/oauth_authorize",
    tokenUrl: "https://app.asana.com/-/oauth_token",
  },
  monday: {
    source: "monday",
    name: "Monday.com",
    description: "Gestión de proyectos",
    type: "oauth2",
    priority: "low",
    scopes: ["boards:read", "boards:write", "users:read"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  canva: {
    source: "canva",
    name: "Canva",
    description: "Diseño",
    type: "oauth2",
    priority: "low",
    scopes: ["design:read", "design:write"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
};

export function getConnectorDefinition(source: IntegrationSource): ConnectorDefinition {
  const def = CONNECTOR_DEFINITIONS[source];
  if (!def) throw new Error(`Conector no registrado: ${source}`);
  return def;
}

export function listConnectorDefinitions(): ConnectorDefinition[] {
  return Object.values(CONNECTOR_DEFINITIONS);
}
