// ==================== CONNECTOR REGISTRY ====================
// Definiciones estáticas de conectores disponibles: metadata, scopes y acciones.

import type { ConnectorDefinition, IntegrationSource } from "./types";

export const CONNECTOR_DEFINITIONS: Record<IntegrationSource, ConnectorDefinition> = {
  figma: {
    source: "figma",
    name: "Figma",
    description: "Importar diseños de Figma",
    type: "rest",
    priority: "high",
    scopes: ["file_read"],
    actions: [
      { name: "listFiles", description: "Listar archivos recientes", params: [{ name: "limit", type: "number", required: false, description: "Máximo de archivos" }] },
      { name: "getFile", description: "Obtener detalle de un archivo", params: [{ name: "fileKey", type: "string", required: true }] },
    ],
    supportsOAuth: false,
    supportsApiKey: true,
  },
  local: {
    source: "local",
    name: "Archivos locales",
    description: "Subir y gestionar archivos locales",
    type: "rest",
    priority: "high",
    scopes: [],
    actions: [
      { name: "upload", description: "Subir un archivo", params: [{ name: "file", type: "object", required: true }] },
      { name: "list", description: "Listar archivos subidos", params: [] },
    ],
    supportsOAuth: false,
    supportsApiKey: false,
  },
  onedrive: {
    source: "onedrive",
    name: "OneDrive",
    description: "Importar archivos de OneDrive",
    type: "oauth2",
    priority: "medium",
    scopes: ["Files.Read"],
    actions: [{ name: "listFiles", description: "Listar archivos", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
    authUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
  },
  "google-drive": {
    source: "google-drive",
    name: "Google Drive",
    description: "Importar archivos de Google Drive",
    type: "oauth2",
    priority: "medium",
    scopes: ["https://www.googleapis.com/auth/drive.readonly", "https://www.googleapis.com/auth/drive.file"], // Added drive.file for reading content
    actions: [
      { name: "listFiles", description: "Listar archivos", params: [{ name: "limit", type: "number", required: false }, { name: "query", type: "string", required: false }] },
      { name: "getResource", description: "Obtener detalle de un archivo", params: [{ name: "id", type: "string", required: true }] },
      { name: "readFile", description: "Leer contenido de un archivo", params: [{ name: "id", type: "string", required: true }] },
    ],
    supportsOAuth: true,
    supportsApiKey: false,
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
  },
  skill: {
    source: "skill",
    name: "Habilidades",
    description: "Habilidades internas del agente",
    type: "rest",
    priority: "low",
    scopes: [],
    actions: [
      { name: "listSkills", description: "Listar habilidades disponibles", params: [] },
      { name: "executeSkill", description: "Ejecutar una habilidad por nombre", params: [{ name: "name", type: "string", required: true }, { name: "action", type: "string", required: false, description: "Acción específica de la habilidad (ej. 'execute', 'info')" }, { name: "params", type: "object", required: false, description: "Parámetros adicionales para la habilidad" }] },
    ],
    supportsOAuth: false,
    supportsApiKey: false,
  },
  slack: {
    source: "slack",
    name: "Slack",
    description: "Enviar notificaciones y mensajes",
    type: "oauth2",
    priority: "high",
    scopes: ["chat:write", "channels:read", "users:read"],
    actions: [
      { name: "sendMessage", description: "Enviar mensaje a un canal", params: [{ name: "channel", type: "string", required: true }, { name: "text", type: "string", required: true }] },
      { name: "listChannels", description: "Listar canales", params: [{ name: "limit", type: "number", required: false }] },
    ],
    supportsOAuth: true,
    supportsApiKey: true,
    authUrl: "https://slack.com/oauth/v2/authorize",
    tokenUrl: "https://slack.com/api/oauth.v2.access",
  },
  gmail: {
    source: "gmail",
    name: "Gmail",
    description: "Enviar emails",
    type: "oauth2",
    priority: "high",
    scopes: ["https://www.googleapis.com/auth/gmail.send", "https://www.googleapis.com/auth/gmail.readonly"],
    actions: [
      { name: "sendEmail", description: "Enviar email", params: [{ name: "to", type: "string", required: true }, { name: "subject", type: "string", required: true }, { name: "body", type: "string", required: true }, { name: "html", type: "boolean", required: false }] },
      { name: "listLabels", description: "Listar etiquetas", params: [] },
    ],
    supportsOAuth: true,
    supportsApiKey: false,
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
  },
  github: {
    source: "github",
    name: "GitHub",
    description: "Issues, repos y PRs",
    type: "oauth2",
    priority: "high",
    scopes: ["repo", "read:user", "user:email"],
    actions: [
      { name: "createIssue", description: "Crear un issue", params: [{ name: "owner", type: "string", required: true }, { name: "repo", type: "string", required: true }, { name: "title", type: "string", required: true }, { name: "body", type: "string", required: false }] },
      { name: "listRepos", description: "Listar repositorios", params: [{ name: "limit", type: "number", required: false }] },
    ],
    supportsOAuth: true,
    supportsApiKey: true,
    authUrl: "https://github.com/login/oauth/authorize",
    tokenUrl: "https://github.com/login/oauth/access_token",
  },
  notion: {
    source: "notion",
    name: "Notion",
    description: "Gestión de documentos",
    type: "oauth2",
    priority: "high",
    scopes: [],
    actions: [
      { name: "listPages", description: "Listar páginas", params: [{ name: "limit", type: "number", required: false }] },
      { name: "createPage", description: "Crear página", params: [{ name: "parentId", type: "string", required: true }, { name: "title", type: "string", required: true }, { name: "content", type: "string", required: false }] },
    ],
    supportsOAuth: true,
    supportsApiKey: true,
    authUrl: "https://api.notion.com/v1/oauth/authorize",
    tokenUrl: "https://api.notion.com/v1/oauth/token",
  },
  "google-sheets": {
    source: "google-sheets",
    name: "Google Sheets",
    description: "Lectura/escritura de datos",
    type: "oauth2",
    priority: "high",
    scopes: ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive.readonly"],
    actions: [
      { name: "listSpreadsheets", description: "Listar hojas de cálculo", params: [{ name: "limit", type: "number", required: false }] },
      { name: "readRange", description: "Leer rango", params: [{ name: "spreadsheetId", type: "string", required: true }, { name: "range", type: "string", required: true }] },
      { name: "writeRange", description: "Escribir rango", params: [{ name: "spreadsheetId", type: "string", required: true }, { name: "range", type: "string", required: true }, { name: "values", type: "array", required: true }] },
    ],
    supportsOAuth: true,
    supportsApiKey: false,
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
  },
  discord: {
    source: "discord",
    name: "Discord",
    description: "Mensajes",
    type: "bot",
    priority: "medium",
    scopes: ["bot"],
    actions: [
      { name: "sendMessage", description: "Enviar mensaje a un canal", params: [{ name: "channelId", type: "string", required: true }, { name: "content", type: "string", required: true }] },
    ],
    supportsOAuth: true,
    supportsApiKey: true,
    authUrl: "https://discord.com/oauth2/authorize",
    tokenUrl: "https://discord.com/api/oauth2/token",
  },
  telegram: {
    source: "telegram",
    name: "Telegram",
    description: "Mensajes vía Bot API",
    type: "bot",
    priority: "medium",
    scopes: [],
    actions: [
      { name: "sendMessage", description: "Enviar mensaje", params: [{ name: "chatId", type: "string", required: true }, { name: "text", type: "string", required: true }] },
    ],
    supportsOAuth: false,
    supportsApiKey: true,
  },
  // --- eCommerce ---
  shopify: {
    source: "shopify",
    name: "Shopify",
    description: "Gestión de productos y órdenes",
    type: "rest",
    priority: "low",
    scopes: ["read_products", "read_orders"],
    actions: [
      { name: "listProducts", description: "Listar productos", params: [{ name: "limit", type: "number", required: false }] },
    ],
    supportsOAuth: true,
    supportsApiKey: true,
  },
  stripe: {
    source: "stripe",
    name: "Stripe",
    description: "Pagos y clientes",
    type: "rest",
    priority: "low",
    scopes: [],
    actions: [
      { name: "listCustomers", description: "Listar clientes", params: [{ name: "limit", type: "number", required: false }] },
    ],
    supportsOAuth: false,
    supportsApiKey: true,
  },
  paypal: {
    source: "paypal",
    name: "PayPal",
    description: "Pagos",
    type: "oauth2",
    priority: "low",
    scopes: ["openid", "profile", "email"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  woocommerce: {
    source: "woocommerce",
    name: "WooCommerce",
    description: "Productos y órdenes de WooCommerce",
    type: "rest",
    priority: "low",
    scopes: [],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: false,
    supportsApiKey: true,
  },
  square: {
    source: "square",
    name: "Square",
    description: "Pagos y catálogo",
    type: "oauth2",
    priority: "low",
    scopes: ["ITEMS_READ", "ORDERS_READ", "CUSTOMERS_READ"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  // --- CRM / Marketing ---
  salesforce: {
    source: "salesforce",
    name: "Salesforce",
    description: "CRM",
    type: "oauth2",
    priority: "low",
    scopes: ["api", "refresh_token"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  hubspot: {
    source: "hubspot",
    name: "HubSpot",
    description: "CRM y marketing",
    type: "oauth2",
    priority: "low",
    scopes: ["crm.objects.contacts.read", "crm.objects.contacts.write"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  mailchimp: {
    source: "mailchimp",
    name: "Mailchimp",
    description: "Email marketing",
    type: "oauth2",
    priority: "low",
    scopes: [],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: true,
  },
  klaviyo: {
    source: "klaviyo",
    name: "Klaviyo",
    description: "Email/SMS marketing",
    type: "oauth2",
    priority: "low",
    scopes: ["accounts:read", "lists:read", "profiles:read"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  pipedrive: {
    source: "pipedrive",
    name: "Pipedrive",
    description: "CRM de ventas",
    type: "oauth2",
    priority: "low",
    scopes: ["base", "deals:full", "contacts:full"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: true,
  },
  // --- Dev / Project Management ---
  gitlab: {
    source: "gitlab",
    name: "GitLab",
    description: "Repositorios e issues",
    type: "oauth2",
    priority: "low",
    scopes: ["api", "read_user"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: true,
  },
  jira: {
    source: "jira",
    name: "Jira",
    description: "Gestión de issues",
    type: "oauth2",
    priority: "low",
    scopes: ["read:jira-work", "write:jira-work", "read:me"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  linear: {
    source: "linear",
    name: "Linear",
    description: "Gestión de issues",
    type: "oauth2",
    priority: "low",
    scopes: ["read", "write"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  vercel: {
    source: "vercel",
    name: "Vercel",
    description: "Despliegues y proyectos",
    type: "oauth2",
    priority: "low",
    scopes: ["projects", "deployments"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  // --- Productivity ---
  asana: {
    source: "asana",
    name: "Asana",
    description: "Gestión de tareas",
    type: "oauth2",
    priority: "low",
    scopes: ["default"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: true,
  },
  monday: {
    source: "monday",
    name: "Monday.com",
    description: "Gestión de proyectos",
    type: "oauth2",
    priority: "low",
    scopes: ["boards:read", "boards:write", "users:read"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
  canva: {
    source: "canva",
    name: "Canva",
    description: "Diseño",
    type: "oauth2",
    priority: "low",
    scopes: ["design:read", "design:write"],
    actions: [{ name: "healthCheck", description: "Verificar conexión", params: [] }],
    supportsOAuth: true,
    supportsApiKey: false,
  },
};

export function getConnectorDefinition(source: IntegrationSource): ConnectorDefinition {
  const def = CONNECTOR_DEFINITIONS[source];
  if (!def) throw new Error(`Conector no registrado: ${source}`);
  return def;
}

export function listConnectorDefinitions(): ConnectorDefinition[] {
  return Object.values(CONNECTOR_DEFINITIONS);
}
